# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8898b4eaaaa33a47d42c6b5e7c09bd8a80852007dff41955c826e38abbc2e1811c541899b74be7a9a2167fdafd031362f25a4eb131c83b04fd05a0b8992fcf56

test:
  secret_key_base: c9a3235a4df6ecdd0074482e44b9c289c5a8f9a4e89685ddbdfded5a99f85e450656d4b620f6d8a961928d1f052da700f482ed9c12dd8349071ee71081497194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
